import { BaseModel } from "app/core/models/base-model";

export interface OrderModel extends BaseModel {
    clientId?: string,
    sendDate?: Date,
    loadingLocation?: string,
    deliveryLocation?: string,
    selectedLocations?: [[]],
    customsPlaceLocation?: string,
    customsClearancePlaceLocation?: string,
    additionalLoadingLocation?: string,
    additionalDeliveryLocation?: string,
    isUrgent?: [true],
    isTwoDays?: [false],
    isAdr?: [false],
    isCarnetTir?: [false],
    isGlonas?: [false],
    isParanom?: [false],
    offeredPrice?: string,
    offeredPriceCurrencyId?: string,
    inAdvancePrice?: [0],
    inAdvancePriceCurrencyId?: string,
    paymentMethod?: ['cash'],
    isSafeTransaction?: [false],
    transportKindIds?: string,
    transportTypeIds?: string,
    refrigeratorFrom?: string,
    refrigeratorTo?: string,
    refrigeratorCount?: string,
    isHook?: string,
    cargoTypeId?: string,
    cargoWeight?: string,
    cargoLength?: string,
    cargoWidth?: string,
    cargoHeight?: string,
    cubature?: string,
    cargoPackageId?: string,
    loadingMethodId?: string
}