version: '3'

services:
  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_NAME=admin-ui
    ports:
      - "4200:80"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/admin-ui/logs
