version: '3.8'
services:
  tirgo-admin-ui:
    container_name: tirgo-admin-ui
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - NGINX_PORT=4200
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./dist/logist-list:/var/www/orders.dafex.co
