name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-admin-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v16
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod -- --output-path=/usr/share/nginx/html/admin-ui

      - name: Set up Docker
        uses: docker/setup-docker@v2.7.0

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tirgodocker/admin-ui:${{ github.sha }}

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose down"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose pull"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose up -d"
