name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-admin-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod -- --output-path=/usr/share/nginx/html/admin-ui

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tirgodocker/admin-ui:${{ github.sha }}

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ SERVER_IP }} "cd ../../ && docker-compose down"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ SERVER_IP }} "cd ../../ && docker-compose pull"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ SERVER_IP }} "cd ../../ && docker-compose up -d"
