name: Angular CI/CD

on:
  push:
    branches: [github-actions]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Copy artifacts
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/

      - name: Install Docker
        uses: actions/setup-docker@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/admin-ui deploy/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add ~/.ssh/deploy_key
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/admin-ui:latest ${{ secrets.DOCKER_USERNAME }}/admin-ui:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/admin-ui:latest

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@ ${{secrets.SERVER_IP}} 'docker pull ${{ secrets.DOCKER_USERNAME }}/admin-ui:latest && docker run -d -p 4200:80 ${{ secrets.DOCKER_USERNAME }}/admin-ui:latest'
