name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-admin-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod -- --output-path=/usr/share/nginx/html/admin-ui

      - name: Set up Docker
        run: |
          sudo service docker start
          sudo docker info
          sudo docker build -t myimage:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker tag myimage:latest tirgodocker/admin-ui:${{ github.sha }}
          docker push tirgodocker/admin-ui:${{ github.sha }}

      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose down"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose pull"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.SERVER_IP }} "cd ../../ && docker-compose up -d"
